# Load config files matching the /etc/chrony/conf.d/*.conf pattern.
confdir /etc/chrony/conf.d

# Use public NTP servers from the pool.ntp.org project.
# Please consider joining the pool project if possible by running your own
# server(s).
# If you are a vendor distributing a product using chrony, you *MUST*
# read and comply with http://www.pool.ntp.org/vendors.html
pool 0.openembedded.pool.ntp.org iburst

# Use a local timeserver in preference to the pool, if it's reachable.
#server 192.168.22.22 iburst minpoll 2 prefer

# Sync to pulse-per-second from an onboard GPS.
#refclock PPS /dev/pps0 poll 0 prefer
# You'll want to enable CONFIG_PPS and CONFIG_PPS_CLIENT_GPIO in your kernel,
# and an entry something like this in your device tree:
#       pps {
#               compatible = "pps-gpio";
#               gpios = <&ps7_gpio_0 56 0>;
#       };

# Load source files matching the /etc/chrony/sources.d/*.sources pattern.
# These can be reloaded using 'chronyc reload sources'.
sourcedir /etc/chrony/sources.d

# Always step the time if it's more than 4ms off.
makestep 0.004 -1

# Record the rate at which the system clock gains/loses time,
# improving accuracy after reboot
driftfile /var/lib/chrony/chrony.drift

# Stop bad estimates upsetting machine clock.
maxupdateskew 100.0

# Enable kernel synchronization of the hardware real-time clock (RTC).
rtcsync

# Allow NTP client access from local network.
#allow 192.168/16

# Serve time even if not synchronized to any NTP server.
#local stratum 10

# Specify file containing keys for NTP authentication.
#keyfile /etc/chrony.keys

# Specify directory for log files.
logdir /var/log/chrony

# Select which information is logged.
#log measurements statistics tracking

# The next 2 settings are used to control how much slewing of the clock chrony
# is allowed to do. The total will be the sum of both and we have a hard limit
# at 500ppm coming from AOS.

# The maximum slewing allowed to correct an offset with the reference clock.
# Note that this value doesn't include corrections due to frequency errors
# (drift).
maxslewrate 200

# Maximum frequency error (drift) of the clock. Chrony will try to compensate
# for drift and this setting limits how large that correction can be.
maxdrift 100

# Get TAI-UTC offset and leap seconds from the system tz database.
# This directive must be commented out when using time sources serving
# leap-smeared time.
leapsectz right/UTC
