MACHINEOVERRIDES =. "jetson-orin-nano-devkit:"
TNSPEC_BOOTDEV ?= "nvme0n1p1"
PARTITION_LAYOUT_TEMPLATE_DEFAULT ?= "flash_t234_qspi.xml"
PARTITION_LAYOUT_TEMPLATE_DEFAULT_SUPPORTS_REDUNDANT ?= "1"
PARTITION_LAYOUT_EXTERNAL_DEFAULT ?= "flash_l4t_t234_nvme.xml"

require conf/machine/include/orin-nano.inc
# No WIFI

KERNEL_ARGS += " net.ifnames=0 systemd.gpt_auto=0 audit=0"
