#@TYPE: Machine
#@NAME: Nvidia Jetson Orin Nano 8GB som on j401 board.
#@DESCRIPTION: Nvidia Jetson Orin Nano devkit using NVMe drive for rootfs

MACHINEOVERRIDES =. "jetson-orin-nano-8gb:"
TNSPEC_BOOTDEV ?= "nvme0n1p1"

require conf/machine/include/orin-nano-som.inc
